version: "3"
services:
  db:
    image: "postgres"
    container_name: "pgdata"
    volumes:
      - "/var/lib/postgresql/data"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cleanerdb
